In [3]:
import numpy as np

向量

In [4]:
x = np.array([1, 2, 3])
print(x)
print(type(x))
print(x.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [5]:
print(x.T)
print(x.T.shape)

[1 2 3]
(3,)


In [11]:
# 计算范数
print(np.linalg.norm(x, ord=2))

3.7416573867739413


In [ ]:
# 矩阵运算
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(A.shape)
B = np.array([[1,3,7],[5,0,2]])
print(B)
print(B.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 3 7]
 [5 0 2]]
(2, 3)


In [13]:
# 1.转置
print(A.T)
print(A.T.shape)


[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [ ]:
# 2.矩阵相加
print(A + B)

[[ 2  5 10]
 [ 9  5  8]]


In [15]:
# 3.矩阵与标量相乘
print(A * 3)


[[ 3  6  9]
 [12 15 18]]


In [16]:
# 4.矩阵相乘
print(A @ B)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)